import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/components/Navbar";
import { NavigationProvider } from "@/src/context/navigationContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({
  style: "normal",
  subsets: ["latin"],
  weight: ["200", "400", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      /* pl-24 relative */
        className={`relative z-50 ${manrope.className}`}
      >
        <NavigationProvider>
        <Navbar />
        {children}
        </NavigationProvider>
      </body>
    </html>
  );
}
